---
- name: Install dependencies
  apt:
    update_cache: true
    install_recommends: false
    name:
      - python3-venv
      - nginx
      - uwsgi
      - uwsgi-plugin-python3
      - memcached
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Create thunes directory
  file:
    path: /var/www/Thunes
    state: directory
    mode: "2775"
    owner: www-data

- name: Clone Thunes repository
  git:
    repo: https://gitlab.crans.org/bombar/thunes.git
    dest: /var/www/Thunes
    track_submodules: yes
    version: master
    umask: "002"
  when: not ansible_check_mode

- name: Deploy settings_local
  template:
    src: settings_local.j2
    dest: /var/www/Thunes/Thunes/settings_local.py
  notify: Reload uwsgi

- name: Install pip requirements
  pip:
    requirements: /var/www/Thunes/requirements.txt
    virtualenv: /var/www/Thunes/.env
    virtualenv_command: pyvenv
    umask: "0002"

- name: Install migrations
  django_manage:
    app_path: /var/www/Thunes
    command: migrate
    virtualenv: /var/www/Thunes/.env

- name: Configure nginx
  file:
    src: /var/www/Thunes/WebUtils/Thunes.nginx
    dest: /etc/nginx/sites-enabled/Thunes.nginx
    state: link
  when: not ansible_check_mode
  notify: Reload nginx

- name: Remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: not ansible_check_mode
  notify: Reload nginx

- name: Configure uwsgi
  file:
    src: /var/www/Thunes/WebUtils/Thunes.uwsgi
    dest: /etc/uwsgi/apps-enabled/Thunes.ini
    state: link
  when: not ansible_check_mode
  notify: Reload uwsgi
