---
- name: Install dependencies
  apt:
    update_cache: true
    install_recommends: false
    name:
      - python3-venv
      - nginx
      - uwsgi
      - uwsgi-plugin-python3
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Create thunes directory
  file:
    path: /var/www/MathoosHouse
    state: directory
    mode: "2775"
    owner: www-data

- name: Clone Thunes repository
  git:
    repo: https://gitea.servens.org/bombar/MathoosHouse.git
    dest: /var/www/MathoosHouse
    track_submodules: yes
    version: master
    umask: "002"
  when: not ansible_check_mode

- name: Generate django SECRET_KEY
  shell: python3 -c 'import random; print("".join([random.choice("abcdefghijklmnopqrstuvwxyz0123456789!@#$%&*(-_=+)") for i in range(50)]))'
  register: django_secret_key
  check_mode: false
  changed_when: true

- name: Deploy settings_local
  template:
    src: settings_local.j2
    dest: /var/www/MathoosHouse/MathoosHouse/settings_local.py
  notify: Reload uwsgi

- name: Install pip requirements
  pip:
    requirements: /var/www/MathoosHouse/requirements.txt
    virtualenv: /var/www/MathoosHouse/.env
    virtualenv_command: pyvenv
    umask: "0002"

- name: Install migrations
  django_manage:
    app_path: /var/www/MathoosHouse
    command: migrate
    virtualenv: /var/www/MathoosHouse/.env

- name: Configure nginx
  file:
    src: /var/www/MathoosHouse/WebUtils/MathoosHouse.nginx
    dest: /etc/nginx/sites-enabled/MathoosHouse.nginx
    state: link
  when: not ansible_check_mode
  notify: Reload nginx

- name: Remove default nginx config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  when: not ansible_check_mode
  notify: Reload nginx

- name: Configure uwsgi
  file:
    src: /var/www/MathoosHouse/WebUtils/MathoosHouse.uwsgi
    dest: /etc/uwsgi/apps-enabled/MathoosHouse.ini
    state: link
  when: not ansible_check_mode
  notify: Reload uwsgi
