---
- name: Install common tools
  apt:
    update_cache: true
    install_recommends: false
    name:
      - sudo
      - molly-guard
      - ntp
      - apt
      - apt-file
      - emacs-nox
      - yaml-mode
      - htop
      - zsh
      - aptitude
      - iotop  # monitor i/o
      - tree  # create a graphical tree of files
      - git
      - less
      - needrestart
      - lsb-release
      - dnsutils
      - ldnsutils
      - cloc
  register: apt_result
  retries: 3
  until: apt_result is succeeded


- name: Install bat
  apt:
    deb: https://github.com/sharkdp/bat/releases/download/v0.15.1/bat_0.15.1_amd64.deb
  when: not ansible_check_mode

- name: python3 is better. Eat it.
  command:
    cmd: update-alternatives /usr/bin/python python /usr/bin/python3 40
  when: not ansible_check_mode
