---
- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
  when: not ansible_check_mode

- name: Reload uwsgi
  systemd:
    name: uwsgi
    state: reloaded
  when: not ansible_check_mode
