shell: "bash"
can_sudo: yes

loc_dns_zones:
  - maximebombar.fr:
      master: yes
  - satellist.fr:
      master: yes

cpasswords:
  {
    cmd_name: cpasswords,
    readonly: False,
    smtp: localhost,
    mailfrom: cpasswords <root@maximebombar.fr,
    mailto: bombar@crans.org,
    gpg :
      [
        {
        user: "pollion",
        uid: "bombar@crans.org",
        fingerprint: "C352C156DCCDFD64CFD6577B84EAFB7218C74ED1",
        },
      ],
    roles:
      [
        {
        name: "pollion",
        members: ["pollion"],
        },

        {
        name: "pollion-w",
        members: ["pollion"],
        },
      ],
  }


thunes:
  debug: True
  db_name: "thunes_dev"
  db_user: "thunes_dev"
  db_ip: "localhost"
  db_password: "{{ vault_thunes_dev_db_password }}"
  secret_key: "{{ vault_thunes_dev_django_secret_key }}"

postgresql:
  version: 11
  hosts:
    - [ "thunes_dev", "thunes_dev", "127.0.0.1/32", null ]
    - [ "thunes_dev", "thunes_dev", "::1/128", null ]
