---
- name: Install bind9
  apt:
    update_cache: true
    name:
      - bind9
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Deploy config
  template:
    src: 'etc/bind/{{ item.src }}'
    dest: '/etc/bind/{{ item.dest }}'
    owner: root
    group: bind
  with_items:
    - { src: 'named.conf.local.j2', dest: 'named.conf.local' }
  notify: Restart bind

- name: Deploy zones
  template:
    src: "var/cache/bind/db.{{ item[0] }}.j2"
    dest: "/var/cache/bind/db.{{ item[0] }}"
    owner: root
    group: bind
  when:
    -  item[1].master
  loop: "{{ dns_zones.items() }}"
  notify: Restart bind

- name: Ensures Zone directory exists
  file:
    path: /etc/bind/zones/
    state: directory
    mode: 0755

- name: Symlink zone files
  file:
    src: /var/cache/bind/db.{{ item[0] }}
    dest: /etc/bind/zones/db.{{ item[0] }}
    state: link
  when:
    - item[1].master
  loop: "{{ dns_zones.items() }}"

- name: Deploy ACME zones
  template:
    src: "var/cache/bind/db.acme.j2"
    dest: "/var/cache/bind/db._acme-challenge.{{ item[0] }}"
    owner: root
    group: bind
  when:
    - item[1].master and item[1].acme
  loop: "{{ dns_zones.items() }}"
  notify: Restart bind

- name: Symlink ACME zone files
  file:
    src: /var/cache/bind/db._acme-challenge.{{ item[0] }}
    dest: /etc/bind/zones/db._acme-challenge.{{ item[0] }}
    state: link
  when:
    - item[1].master
  loop: "{{ dns_zones.items() }}"
