---
- name: Deploy ssh key
  authorized_key:
    user: "{{ ansible_user }}"
    comment: Maxime Bombar (bombar@crans.org) - Poincare
    exclusive: yes
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILlvuevXcRtS/qfxSZg6/EGiNEHeMA55G92itIkhMRMZ

- name: Clone Config_Files
  git:
    repo: https://gitlab.crans.org/bombar/Config_Files.git
    dest: ~/Git/Config_Files
    track_submodules: yes
    version: master
    umask: "022"
  when: not ansible_check_mode and ansible_connection == "local"

- name: Clone Config_Files
  git:
    repo: https://gitlab.crans.org/bombar/Config_Files.git
    dest: ~/Git/Config_Files
    track_submodules: no
    version: master
    umask: "022"
  when: not ansible_check_mode and not ansible_connection == "local"

- name: Find ssh configuration
  find:
    paths: ~/Git/Config_Files/.ssh
    patterns: config*
  register: ssh_config
  when: not ansible_check_mode

- name: Deploy ssh configuration
  file:
    src: ~/Git/Config_Files/.ssh/{{ item.path | basename }}
    dest: ~/.ssh/{{ item.path | basename }}
    state: link
  loop: "{{ ssh_config.files }}"
  when: not ansible_check_mode

- name: Deploy .gitconfig
  file:
    src: ~/Git/Config_Files/.gitconfig
    dest: ~/.gitconfig
    state: link
  when: not ansible_check_mode

- name: Deploy zsh config
  file:
    src: ~/Git/Config_Files/{{ item }}
    dest: ~/{{ item }}
    state: link
  loop:
    - .zshrc
    - .zsh
  when: shell == "zsh" and not ansible_check_mode

- name: Deploy bash config
  file:
    src: ~/Git/Config_Files/{{ item }}
    dest: ~/{{ item }}
    state: link
  loop:
    - .umaskrc
    - .bashrc
    - .bash_aliases
  when: shell == "bash" and not ansible_check_mode

- name: No install recommands apt
  template:
    src: apt/apt.conf.d/99no-install-recommends
    dest: /etc/apt/apt.conf.d/99no-install-recommends
  become: yes
