---
- name: Deploy ssh key
  authorized_key:
    user: "{{ ansible_user }}"
    comment: Maxime Bombar (bombar@crans.org) - Poincare
    exclusive: no
    key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILZ5sU8rUfwe72C6k/xS0ffsKs0rr4KITeVfk4ZeFmP3

- name: Clone Config_Files
  git:
    repo: https://gitlab.crans.org/bombar/Config_Files.git
    dest: /home/{{ ansible_user }}/Git/Config_Files
    track_submodules: yes
    version: master
    umask: "022"
  when: not ansible_check_mode

- name: Find ssh configuration
  find:
    paths: /home/{{ ansible_user }}/Git/Config_Files/.ssh
    patterns: config*
  register: ssh_config
  when: not ansible_check_mode

- name: Deploy ssh configuration
  file:
    src: /home/{{ ansible_user}}/Git/Config_Files/.ssh/{{ item.path | basename }}
    dest: /home/{{ ansible_user }}/.ssh/{{ item.path | basename }}
    state: link
  loop: "{{ ssh_config.files }}"
  when: not ansible_check_mode

- name: Deploy .gitconfig
  file:
    src: /home/{{ ansible_user}}/Git/Config_Files/.gitconfig
    dest: /home/{{ ansible_user }}/.gitconfig
    state: link
  when: not ansible_check_mode

- name: Deploy .emacs
  file:
    src: /home/{{ ansible_user}}/Git/Config_Files/.emacs_simple
    dest: /home/{{ ansible_user }}/.emacs
    state: link
  when: not ansible_check_mode

- name: Deploy zsh config
  file:
    src: /home/{{ ansible_user}}/Git/Config_Files/{{ item }}
    dest: /home/{{ ansible_user }}/{{ item }}
    state: link
  loop:
    - .zshrc
    - .zsh
  when: shell == "zsh" and not ansible_check_mode

- name: Deploy bash config
  file:
    src: /home/{{ ansible_user}}/Git/Config_Files/{{ item }}
    dest: /home/{{ ansible_user }}/{{ item }}
    state: link
  loop:
    - .umaskrc
    - .bashrc
    - .bash_aliases
  when: shell == "bash" and not ansible_check_mode
